### ISSUE TITLE
Show BareMetalHost CRD

### ISSUE THREAD

**Issue by stbenjam** [elmiko/camgi.rs#19]
Wow, this tool is great!

For bare metal clusters, there's additional machine-related resource called BareMetalHost that represents the physical hardware available for machines.  Is there any chance these could be shown on that page?

**Comment by elmiko** [comment]
hi @stbenjam , thanks!

yeah it's certainly possible, i'm not overly familiar with that record but i can certainly investigate adding it. do you happen to have a link to the openshift/api so i could read more?

**Comment by stbenjam** [comment]
The CRD comes from the baremetal-operator https://github.com/openshift/baremetal-operator/blob/master/apis/metal3.io/v1alpha1/baremetalhost_types.go#L784

A simple UI just showing the BMH name and expanding to dump the YAML would be sufficient

**Comment by elmiko** [comment]
thanks!

**Comment by elmiko** [comment]
closed by #22
