### ISSUE TITLE
Add info about underlying infrastructure on the `Summary` page

### ISSUE THREAD

**Issue by lobziik** [elmiko/camgi.rs#30]
It would be cool to have info extracted from the OCP infrastructure resource, like the platform type on the `Summary` page.

Given that camgi is used within the OCP ci, this will simplify access to such information.

**Comment by elmiko** [comment]
i had wanted to recreate some of the resource totals on the summary page as well, but at the time the rust support for `resource.Quantity` wasn't that great. i think it's gotten better since then.
